import Inter from '@/components/Inter'
import { ClerkLoaded, UserButton } from '@clerk/nextjs'
import { Breadcrumbs, Button, Page } from '@geist-ui/core'
import { Inbox, Home as HomeIcon } from '@geist-ui/icons'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import Editor, { Monaco } from "@monaco-editor/react";
import CodeExec from 'code-exec'

export function Navbar () {
  return (
    <nav style={{
      width: '100%',
      height: '64px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      boxSizing: 'border-box',
      padding: '0px 32px'
    }}>

      <Breadcrumbs>
        <Breadcrumbs.Item href="/dashboard"><HomeIcon /></Breadcrumbs.Item>
        {/* <Breadcrumbs.Item href=""><Inbox /> Inbox</Breadcrumbs.Item>
        <Breadcrumbs.Item>Page</Breadcrumbs.Item> */}
      </Breadcrumbs>

      <div>
        <ClerkLoaded>
          <UserButton signInUrl="/sign-in" signUpUrl="/sign-up" userProfileMode="modal" afterSignOutUrl="/" />
        </ClerkLoaded>
      </div>

    </nav>
  )
}

export function Code ({ defaultValue, onChange }) {
  const editorRef = useRef(null);
  
  function handleEditorDidMount(editor, monaco) {
    console.log("editor mounted", editor, monaco);
    editorRef.current = editor;
  }

  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Victor+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
      </Head>
      <Editor
        height="40vh"
        defaultLanguage="javascript"
        theme="vs-dark"
        options={{
          fontFamily: '"Victor Mono"',
          fontSize: 14,
          scrollBeyondLastLine: false
        }}
        defaultValue={defaultValue}
        onMount={handleEditorDidMount}
        onChange={onChange}
      />
    </>
  )
}

export default function Home() {
  const [code, setCode] = useState(`// Vaquero IDE\n// NodeJS v18.15.0"`);

  const [running, setRunning] = useState(false);

  const [output, setOutput] = useState('');

  function run () {
    setRunning(true);
    const start = Date.now();

    CodeExec.with('javascript').run(
      new CodeExec.File('index.js', code)
    ).then(result => {
      setOutput(`Finished in ${Date.now() - start}ms\n\n${result.output}`);

      setRunning(false);
    });
  }

  return (
    <Inter>
      <Head>
        <title>Vaquero IDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Page>
        <Page.Header>
            <h2>Code Repl</h2>
          </Page.Header>
          <Page.Content>
            <h2>Editor</h2>
            <p>Here is an editor for you to write code.</p>
            <Code defaultValue={`// Vaquero IDE\n// NodeJS v18.15.0`} onChange={setCode} />
            <pre><code>{output}</code></pre>
            <Button onClick={run} loading={running} disabled={running} type="success">Run</Button>
          </Page.Content>
      </Page>
    </Inter>
  )
}
