import Inter from '@/components/Inter'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef } from 'react'




export default function Home() {
  return (
    <Inter>
      <Head>
        <title>Vaquero IDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        width: '100vw',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <div style={{
          textAlign: 'center'
        }}>
          <h1>Vaquero IDE</h1>
          <h2>Sign In</h2>
          <a href="/sign-in/">Sign In</a>
          <p>Shared hosting for Irvine Hack Club</p>
        </div>
      </div>
    </Inter>
  )
}
