import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useRef } from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        width: '100vw',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: 'Inter, system-ui, sans-serif'
      }}>
        <div style={{
          textAlign: 'center'
        }}>
          <h1>vaquero.dev</h1>
          <h2>🚧 Coming Soon 🚧</h2>
          <p>Shared hosting for Irvine Hack Club</p>
        </div>
      </div>
    </>
  )
}
