import Inter from '@/components/Inter'
import { Button } from '@geist-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef } from 'react'




export default function Home() {
    return (
        <Inter>
            <Head>
                <title>About vaquero.dev</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <style dangerouslySetInnerHTML={{
                    __html: /*css*/`
            body {
                width: 100vw;
                height: 100vh;
                background: url("https://cloud-8lj4t1m8o-hack-club-bot.vercel.app/0image__45_-min__1_.png");
                background-size: cover;
                overflow: hidden;
            }

            div#main { /* page */
                background: white;
                width: min(calc(100vw - 100px), 1200px);
                height: 100vh;
                overflow-y: scroll;
                padding: 48px 56px;
                box-sizing: border-box;
                color: black!important;
            }

            div#main * {
                color: black;
                position: relative;
            }

            div#main h1 {
                text-align: center;
            }
        ` }} />
            </Head>
            <div style={{
                width: '100vw',
                height: '100vh',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'end',
                color: 'black'
            }}>
                <div id="main">
                <h2>vaquero.dev Privacy Policy</h2>
<strong>Last Updated: July 6, 2024</strong>

<p>Welcome to vaquero.dev! We value your privacy and are committed to protecting your personal information. This Privacy Policy outlines our practices regarding the collection, use, and protection of your data. Please read it carefully before using the vaquero.dev app, accessible via the website editor.vaquero.dev, or by visiting our homepage at vaquero.dev (hereinafter referred to as the "App" or "Website"). By using our services, you agree to the terms outlined in this Privacy Policy.</p>

<h3>1. Data Responsibility and Security</h3>
<p>1.1 <strong>Data Breach Disclaimer</strong>: vaquero.dev, its developers, and associates are not responsible for any data breaches or any other events related to the App. The security of your personal data is important to us, but remember that no method of transmission over the internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data and the protection of your data is our top priority, we cannot guarantee its absolute security.</p>

<p>1.2 <strong>Security Assurance</strong>: We have implemented security measures to the best of our ability at the time of development to safeguard your data.</p>

<h3>2. Data Collection</h3>
<p>2.1 <strong>Cookies</strong>: The App uses cookies, and users must comply with our cookie policy to use the App.</p>

<p>2.2 <strong>Data Collected: vaquero.dev collects the following data</strong>: name, email, and Microsoft account details during the sign-up process.</p>

<p>2.3 <strong>Optional Data</strong>: You may choose to provide additional information within the App at your own discretion. Other data not listed here might also be collected.</p>

<p>2.4 <strong>IP Address</strong>: The App and its third-party providers may log your IP address when accessing the App for security purposes.</p>

<h3>3. Data Use and Retention</h3>
<p>3.1 <strong>Purpose of Collection</strong>: We collect data for the purpose of providing services to end-users, managing profiles, and other related activities.</p>

<p>3.2 <strong>No Data Sale</strong>: vaquero.dev will not sell your personal data to third parties.</p>

<p>3.3 <strong>Third-party Analytics</strong>: We may use third-party analytics platforms to gather information about App usage, but this data is anonymized and not linked to your personal identity.</p>

<p>3.4 <strong>Data Encryption</strong>: Some of your data is encrypted with AES-256 GCM for enhanced security.</p>

<p>3.5 <strong>User-Generated Data</strong>: User-generated data, such as tasks created, will be stored until you choose to delete it.</p>

<p>3.6 <strong>Account Deletion</strong>: You can delete your account by contacting us at 949.409.1560 or via our in-app settings.</p>

<p>3.7 <strong>Data Retention</strong>: Your data will be stored as long as you maintain an active account with us.</p>

<h3>4. Third-party Links and Integrations</h3>
<p>4.1 <strong>Third-party Links</strong>: We are not responsible for in-app links or user-generated data that may lead to third-party websites.</p>

<p>4.2 <strong>Integrations</strong>: vaquero.dev is not responsible for the security of third-party integrations used within the App.</p>

<h3>5. Legal Compliance</h3>
<p>5.1 <strong>Laws and Regulations</strong>: vaquero.dev is designed to comply with US laws and regulations, and we are not responsible for any restrictions imposed by other countries.</p>

<p>5.2 <strong>Minimum Age</strong>: Users must be at least 13 years old to use vaquero.dev.</p>

<h3>6. Accessibility and Payments</h3>
<p>6.1 <strong>Accessibility</strong>: The App is designed to the best of our ability to ensure accessibility.</p>

<p>6.2 <strong>Payments/Financial Info</strong>: vaquero.dev does not accept payments or engage in any form of monetization at this time.</p>

<h3>7. User Rights</h3>
<p>7.1 <strong>User Rights</strong>: You have the right to permanently delete your data from our systems.</p>

<p>7.2 <strong>Consent</strong>: Users can delete their content, which will remove it from our system.</p>

<h3>8. Updates and Changes</h3>
<p>8.1 <strong>Policy Updates</strong>: This Privacy Policy may be updated at any time. Please review it periodically for changes.</p>

<h3>9. International Data Transfer</h3>
<p>9.1 <strong>International Data Transfer</strong>: User-generated content may be transferred to servers located in different countries for processing.</p>

<h3>10. Dispute Resolution</h3>
<p>10.1 <strong>Disputes</strong>: vaquero.dev is not responsible for disputes, but you may contact us at 949.409.1560 for assistance.</p>

<h3>11. Acceptance of Terms</h3>
<p>11.1 <strong>Acceptance</strong>: By signing up for vaquero.dev, you agree to comply with the terms outlined in this Privacy Policy.</p>

<h3>12. Data Protection Officer</h3>
<p>12.1 <strong>Data Protection Officer</strong>: vaquero.dev has not appointed a Data Protection Officer.</p>

If you have any questions or concerns regarding this Privacy Policy or our data practices, please contact us at 949.409.1560.

Thank you for using vaquero.dev! Your privacy and security are important to us.



                  </div>
            </div>
        </Inter>
    )
}
